name: Build Theme
'on':
  push:
    branches:
    - main
    - develop
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install gitversion
      uses: gittools/actions/gitversion/setup@v0.9.6
      with:
        versionSpec: 5.x
    - id: gitversion
      name: Use gitversion
      uses: gittools/actions/gitversion/execute@v0.9.6
      with:
        useConfigFile: true
        configFilePath: ./gitversion.yml
    - name: Display version
      run: 'echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"'
  build-firefox:
    needs:
    - version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Bump manifest version
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: '"version": ".+"'
        replace: '"version": "${{ needs.version.outputs.version }}"'
        regex: true
    - run: zip theme.xpi manifest.json
    - uses: actions/upload-artifact@master
      with:
        name: theme-xpi
        path: ./theme.xpi
  build-chrome:
    needs:
    - version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Bump manifest version
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: '"version": ".+"'
        replace: '"version": "${{ needs.version.outputs.version }}"'
        regex: true
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: python rewrite-manifest.py
    - env:
        EXTENSION_KEY: ${{ secrets.CHROME_SIGNING_KEY }}
      uses: BenMMcLean/pack-chromium-extension@v1.0.1
      with:
        input-folder: chrome
        output-file: theme.crx
    - run: ls -l .
    - run: cat theme.crx
    - uses: actions/upload-artifact@master
      with:
        name: theme-crx
        path: ./theme.crx
