name: Build Theme
'on':
  push:
    branches:
    - main
    - develop
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install gitversion
      uses: gittools/actions/gitversion/setup@v0.9.6
      with:
        versionSpec: 5.x
    - id: gitversion
      name: Use gitversion
      uses: gittools/actions/gitversion/execute@v0.9.6
      with:
        useConfigFile: true
        configFilePath: ./gitversion.yml
    - name: Display version
      run: 'echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"'
  release-firefox:
    permissions:
      contents: write
    needs:
    - version
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: create_release
      name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ needs.version.outputs.version }}
        name: Release ${{ needs.version.outputs.version }}
        target_commitish: ${{ github.sha }}
        draft: false
        prerelease: ${{ github.ref != 'refs/heads/main' }}
  build-firefox:
    needs:
    - version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Bump manifest version
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: '"version": ".+"'
        replace: '"version": "${{ needs.version.outputs.version }}"'
        regex: true
    - run: zip theme.xpi manifest.json
    - uses: actions/upload-artifact@master
      with:
        name: theme-xpi
        path: ./theme.xpi
  build-chrome:
    needs:
    - version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Bump manifest version
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: '"version": ".+"'
        replace: '"version": "${{ needs.version.outputs.version }}"'
        regex: true
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: python rewrite-manifest.py
    - env:
        EXTENSION_KEY: ${{ secrets.CHROME_SIGNING_KEY }}
      uses: BenMMcLean/pack-chromium-extension@v1
      with:
        input-folder: chrome
        output-file: theme.crx
    - uses: actions/upload-artifact@master
      with:
        name: theme-crx
        path: ./theme.crx
  publish-firefox-release:
    permissions:
      contents: write
    needs:
    - version
    - release
    - build-firefox
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: theme-xpi
        path: ./
    - name: Upload Artifact to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./theme.xpi
        asset_name: witchy-hazel-v${{ needs.version.outputs.version }}.unsigned.zip
        asset_content_type: application/zip
    - name: Upload Artifact to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./theme.xpi
        asset_name: witchy-hazel-v${{ needs.version.outputs.version }}.unsigned.xpi
        asset_content_type: application/zip
  publish-chrome-release:
    permissions:
      contents: write
    needs:
    - version
    - release
    - build-chrome
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: theme-crx
        path: ./
    - name: Upload Artifact to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./theme.crx
        asset_name: witchy-hazel-v${{ needs.version.outputs.version }}.crx
        asset_content_type: application/x-chrome-extension
